環境自動セットアップシステムの追加
noko1024/e-auto pull request #32
Opened 2020-12-04 16:17 UTC by noko1024

pipからseleniumのinstallまですべて一括で行えるプログラムの追加

2020-12-04 16:18 UTC, yugu0202 approved these changes

2020-12-05 04:25 UTC, yugu0202 requested changes
e-auto.payの変更はdevByYuguにpushするか
devByYuguがmasterにmergeされた後にpushしてください

2020-12-05 05:49 UTC, polyacetal approved these changes

2020-12-05 05:54 UTC, noko1024 commented
先にそちらの変更をマージしてほしい

2020-12-05 06:19 UTC, merged